// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCGuVB8bh4vtl6oVoth93z3Bl9W1SyTXP4',
    appId: '1:940146718413:web:a70d2057d334ea80cf9b84',
    messagingSenderId: '940146718413',
    projectId: 'moovie-app-task',
    authDomain: 'moovie-app-task.firebaseapp.com',
    storageBucket: 'moovie-app-task.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAmlLkOQX87_rD7XL8VHVurMlS1l_eC2bs',
    appId: '1:940146718413:android:4e176b5721215cabcf9b84',
    messagingSenderId: '940146718413',
    projectId: 'moovie-app-task',
    storageBucket: 'moovie-app-task.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDekIbk0wodhZvzfgLR3277QGGmQl6SYnQ',
    appId: '1:940146718413:ios:6ec8c6b495982176cf9b84',
    messagingSenderId: '940146718413',
    projectId: 'moovie-app-task',
    storageBucket: 'moovie-app-task.appspot.com',
    iosBundleId: 'com.example.moovie',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDekIbk0wodhZvzfgLR3277QGGmQl6SYnQ',
    appId: '1:940146718413:ios:4ce2612cb9081262cf9b84',
    messagingSenderId: '940146718413',
    projectId: 'moovie-app-task',
    storageBucket: 'moovie-app-task.appspot.com',
    iosBundleId: 'com.example.moovie.RunnerTests',
  );
}
